#---------------------------------------------------------------------------#
# This file is part of PSYDAC which is released under MIT License. See the  #
# LICENSE file or go to https://github.com/pyccel/psydac/blob/devel/LICENSE #
# for full license details.                                                 #
#---------------------------------------------------------------------------#
import pytest


@pytest.mark.pyccel
def test_epyccel_flags():

    from pyccel import epyccel
    from psydac.api.settings import PSYDAC_BACKENDS

    # Select the Pyccel backend which uses the GCC compilers
    backend = PSYDAC_BACKENDS['pyccel-gcc']

    # Arguments for `epyccel`
    kwargs = {'language'     : 'fortran',
              'compiler_family' : backend['compiler_family'],
              'flags'        : backend['flags'],
              'openmp'       : backend['openmp'],
              'verbose'      : True,
              }

    # Function to be Pyccel-ized
    def f(x : float):
        return 3 * x

    # Pyccel magic
    # ------------
    # Fortran code is generated and then compiled with the selected compiler family.
    # The compiled function is callable from Python through the C Python API.
    # The necessary C wrapper functions are also generated by Pyccel.
    fast_f = epyccel(f, **kwargs)

    # Check output of pyccelized function
    assert fast_f(3.5) == f(3.5)


# Interactive usage
if __name__ == '__main__':
    test_epyccel_flags()
    print('PASSED')
