# this file shows to pytest what to collect
# here we avoid collecting test classes (which are not used in PSYDAC)
# this is to avoid getting the warning on TestFunction
# TODO can we exlude TestFunction from python_classes pattern? 
[pytest]
minversion = 4.5
addopts = --strict-markers
markers =
    mpi: parallel test to be run using 'mpiexec' or 'mpirun'
    petsc: test requiring a working PETSc installation with petsc4py Python bindings
    pyccel: test for checking Pyccel setup on machine

python_files = test_*.py
python_classes = 
python_functions = test_*


[coverage:run]
branch = True
omit =
    ; Exclude pyccelised kernels
    */__psydac__/*

    ; Examples don't need to be covered
    */examples/*

    ; Unit tests shouldn't be included
    */tests/*

[coverage:report]
; Regexes for lines to exclude from consideration
exclude_also =
    ; Don't complain about missing debug-only code:
    def __repr__
    if self\.debug

    ; Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    ; Don't complain if non-runnable code isn't run:
    if False:
    if __name__ == .__main__.:

    ; Don't complain about abstract methods, they aren't run:
    @(abc\.)?abstractmethod

ignore_errors = True

[coverage:html]
directory = coverage_html_report
