name: 'Parallel h5py installation'

runs:
  using: "composite"
  steps:

    - name: Determine directory of parallel HDF5 library
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          HDF5_DIR=$(dpkg -L libhdf5-openmpi-dev | grep libhdf5.so | xargs dirname)
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          HDF5_DIR=$(brew list hdf5-mpi | grep "libhdf5.dylib" | xargs dirname | xargs dirname)
        fi
        echo $HDF5_DIR
        echo "HDF5_DIR=$HDF5_DIR" >> $GITHUB_ENV

    - name: Install h5py in parallel mode
      shell: bash
      run: |
        export CC="mpicc"
        export HDF5_MPI="ON"
        pip install h5py --no-cache-dir --no-binary h5py
        pip list

    - name: Check parallel h5py installation
      shell: bash
      run: |
          python -c "
          from mpi4py import MPI
          import h5py
          # This particular instantiation of h5py.File will fail if parallel h5py isn't installed
          f = h5py.File('parallel_test.hdf5', 'w', driver='mpio', comm=MPI.COMM_WORLD)
          print(f)"
