name: 'Install PETSc and petsc4py'
description: 'Install PETSc and petsc4py with complex support'

runs:
  using: "composite"
  steps:

    - name: Cache PETSc
      uses: actions/cache@v4
      id: cache-petsc
      env:
        cache-name: cache-PETSc
      with:
        path: "./petsc"
        key: petsc-${{ matrix.os }}-${{ matrix.python-version }}

    - if: steps.cache-petsc.outputs.cache-hit != 'true'
      name: Download a specific release of PETSc
      shell: bash
      run: |
        git clone --depth 1 --branch v3.25.4 https://gitlab.com/petsc/petsc.git
      # The branch "release" contains work towards the next version of PETSc,
      # and it may not be stable. If necessary, it can be cloned as follows:
      # git clone --depth 1 --branch release https://gitlab.com/petsc/petsc.git

    - if: steps.cache-petsc.outputs.cache-hit != 'true'
      name: Install PETSc with complex support
      shell: bash
      working-directory: ./petsc
      run: |
        export PETSC_DIR=$(pwd)
        export PETSC_ARCH=petsc-cmplx
        ./configure --with-scalar-type=complex --with-fortran-bindings=0 --have-numpy=1         
        make all
        echo "PETSC_DIR=$PETSC_DIR" > petsc.env
        echo "PETSC_ARCH=$PETSC_ARCH" >> petsc.env

    # This step is not really necessary and could be combined with PETSc install
    # step; however it's good to verify if the cached PETSc installation really works!
    - name: Test PETSc installation
      shell: bash
      working-directory: ./petsc
      run: |
        source petsc.env
        make check
        echo "PETSC_DIR=$PETSC_DIR" >> $GITHUB_ENV
        echo "PETSC_ARCH=$PETSC_ARCH" >> $GITHUB_ENV

    - name: Install petsc4py
      shell: bash
      working-directory: ./petsc
      run: | 
        pip install wheel Cython numpy
        pip install src/binding/petsc4py
