name: Documentation

on:
  push:
    branches: [ devel ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'psydac/**.py'

  pull_request:
    branches: [ devel, main ]
    types:
      - ready_for_review

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}
      OMP_NUM_THREADS: 2

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install non-Python dependencies on Ubuntu
      uses: ./.github/actions/ubuntu_install

    - name: Print information on MPI and HDF5 libraries
      run: |
        ompi_info
        h5pcc -showconfig -echo || true

    - name: Upgrade pip, setuptools, and wheel
      run: |
        pip install --upgrade pip setuptools wheel

    - name: Install PETSc and petsc4py with complex support
      uses: ./.github/actions/install_petsc4py

    - name: Install h5py in parallel mode
      uses: ./.github/actions/install_h5py

    - name: Install project
      run: |
        pip install .[test]
        pip freeze

    - name: Install non-Python dependencies for Documentation
      run: |
        sudo apt install graphviz pandoc

    - name: Install Python dependencies for Documentation
      run: |
        pip install -r docs/requirements.txt

    - name: Make the sphinx doc
      run: |
        rm -rf docs/source/modules/STUBDIR
        make -C docs clean
        make -C docs html
        python docs/update_links.py

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs/build/html'

  deploy_docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/devel'
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
