name: sphinx

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install pydata_sphinx_theme
        python -m pip install numpydoc
    - name: Make the sphinx doc
      run: |
        make -C documentation clean
        make -C documentation html
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'documentation/build/html'

  deploy_docs:
    if: github.event_name != 'pull_request'
    needs: build_docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
